spring:
  application:
    name: concert_Reservation_Ticket
  datasource:
    # DB_CLOSE_DELAY=-1 ?????? ??? ?? ?? ?????? ????, DB_CLOSE_ON_EXIT=FALSE ?????? ?? ? ??????? ?? ???? ??
    #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /api/**
  # ?? ??
  logging:
    level:
      root: info
      org:
        hibernate:
          SQL: debug
        springframework:
          web: debug